# TODO see this https://blog.ionelmc.ro/2014/05/25/python-packaging/
# TODO see https://github.com/google/googletest/blob/master/.travis.yml
# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

language: python

# need to use trusty because python3-pip requires 14.04+
matrix:
  include:

    #- os: linux
    #  dist: trusty
    #  sudo: required
    #  python: 3.8-dev
    #  env: PY=3.8

    - os: linux
      dist: trusty
      sudo: required
      python: 3.7-dev
      env: PY=3.7

    - os: linux
      dist: trusty
      sudo: required
      python: 3.6
      env: PY=3.6

    - os: linux
      dist: trusty
      sudo: required
      python: 3.5
      env: PY=3.5

    - os: linux
      dist: trusty
      sudo: required
      python: 3.4
      env: PY=3.4

    # disable tests for 3.3:
    #   * pip is no longer supporting python 3.3: https://pip.pypa.io/en/stable/installing/
    #   * 3.3 development ceased 2017: https://lwn.net/Articles/733165/
    #- os: linux
    #  dist: trusty
    #  sudo: required
    #  python: 3.3
    #  env: PY=3.3

    # OS X tests are *very* slow. enable only one.
    #- os: osx
    #  language: generic
    #  env: PY=3.7 PYENV=3.7-dev

    #- os: osx
    #  language: generic
    #  env: PY=3.6 PYENV=3.6.1

    - os: osx
      language: generic
      env: PY=3.5 PYENV=3.5.1

    #- os: osx
    #  language: generic
    #  env: PY=3.4 PYENV=3.4.1

    #- os: osx
    #  language: generic
    #  env: PY=3.3 PYENV=3.3.1

# command to install dependencies
install:
  - ./.ci/travis_install.sh

# command to run tests
script: ./.ci/travis_test.sh

after_success:
  - cd ./test && codecov
